spring:
  application:
    name: eCare
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect 
        jdbc:
         lob:
          non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect     
#  h2:
#    console:
#      enabled: true    
#      path: /h2_console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: 
#server:
#  port: 8070   
  
  datasource:
   #url: jdbc:postgresql://suchidatabase.c14p4idllno5.us-east-1.rds.amazonaws.com:5432/postgres
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: root
  #  url: jdbc:postgresql://databasesuruchi98546.c14p4idllno5.us-east-1.rds.amazonaws.com:5432/postgres
   # url: jdbc:postgresql://db:5432/postgres
   
   
   # url: jdbc:postgresql://${dbhost}:5432/${POSTGRES_DB}
   # username: ${POSTGRES_USER}
   # password: ${POSTGRES_PASSWORD}
    
#cloud:
# aws:
#   credentials:
#     access-key: AKIAZQLTBJ4PHZVFXWQV
#     secret-key: 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
#   region:
#     static: us-east-1
#     auto: false  